#!/usr/bin/python3

import sys

arguments = sys.argv
test_f = arguments[1]

def findFactore(num):
    factors = []
    for i in range(2, int(num ** 0.5) + 1):
        if num % i == 0:
            factors.append(i)
            factors.append(num // i)
            break
    return factors


try:
    with open(test_f, "r") as file:
        lines = file.readlines()
        list_of_num = []
        for line in lines:
            num = int(line)
            factors = findFactore(num)
            if factors:
                print("{}={}*{}".format(num, factors[0], factors[1]))
except Exception as e:
    print(e)
finally:
    file.close()
